### ISSUE TITLE
what's mean of CoordsManager.create_coords_key?

### ISSUE THREAD

**Issue by asurada404** [NVIDIA/MinkowskiEngine#185]
Can anyone explain more detail or recommend some references about  `CoordsManager.create_coords_key`?

**Comment by chrischoy** [comment]
The ME v0.5 now renamed this to `insert_and_map`. The function creates a hash table that converts a N-dimensional coordinate to a hash key and other required variables to initialize the coordinate manager. The hash table is crucial for spatial operations on sparse tensors including convolution since a random access on a sparse tensor is very time consuming.
