### ISSUE TITLE
Questions about the index mapping of sparse tensor coordinates before and after convolutions

### ISSUE THREAD

**Issue by chronbird** [NVIDIA/MinkowskiEngine#197]
Hi!

Q1: there is a voxelized point cloud called **p** with shape [n, 3], after MinkowskiConvolution, its output is **h** with shape [n', channel]. I can get a coordinate mapping (**m_source**, **m_target**) by get_coords_map by inputing their strides, does each element in m_source represent the index (or order) in **p**?

Q2: now I have a batch of point cloud called **P** with with shape [N, 3], where N=sum(n_i) and n_i is the number of points of the ith sample, after MinkowskiConvolution, its output is **H** with shape [N', 3]. I still can get a coordinate mapping (**M_source**, **M_target**) by get_coords_map by inputing their strides, but how can I get the mapping for the ith sample? 

Thanks.

**Comment by chrischoy** [comment]
Q1: When the stride != [1, 1, 1], the convolution will create a new set of coordinates and yes these are row indices of coordinates and features of p and h respectively.

Q2: It does not support an individual batch-level mapping. However, since you can get the row indices for specific points with `get_row_indices_per_batch` or `get_row_indices_at`, you can combine the provided mapping to get the mapping for specific batch index.

**Comment by chronbird** [comment]
Thanks a lot! It really helps.
