### ISSUE TITLE
SparseTensor.dense() changes the tensor 

### ISSUE THREAD

**Issue by SimplicityApks** [NVIDIA/MinkowskiEngine#201]
Calling `t.dense()` on a sparse tensor modifies its t.C field:

https://github.com/NVIDIA/MinkowskiEngine/blob/2bb627e9e395419ac9f0289c3517b1c0c00500bd/MinkowskiEngine/SparseTensor.py#L896

This is highly unintuitive, as one does not expect this from tensors normally (and it took me hours to fix a bug resulting from it).

As a side note, I also believe the default behavior for the min_coords param may be unintuitive. It should be 0 (and explained in the docstring). It is very surprising that the coordinates t.C don't match the indices into the dense array.

**Comment by chrischoy** [comment]
Thanks for the report. It will be fixed in the v0.5

The generalized sparse tensor does not require the coordinates to be positives and allows flexible data augmentation and process. (No need to set the coordinate minimum to be 0 at all for feed-forward).

Thus, if the coordinates are negative, there's no way to create a dense tensor without translation.
