### ISSUE TITLE
How to say the kernel size, 3*3 or 3*3*3?

### ISSUE THREAD

**Issue by somebodyus** [NVIDIA/MinkowskiEngine#249]
Assume we set kernel size to `3`, and the dimension D to `3` in the minkowski convolution.
Then, how to say the kernel size, `3*3` or `3*3*3`? Which is correct?

**Comment by chrockey** [comment]
By default, kernel shape is HYPERCUBE so 3*3*3 is correct.

**Comment by somebodyus** [comment]
> By default, kernel shape is HYPERCUBE so (3, 3, 3) is correct.

Thank you. But I actually cannot well understand the hyper-cube. 

If we set the dimension D to `3`, we can say the kernel size as `3*3*3` and the kernel shape is a 3-D cube. The convolution convolves the points within the 3-D cube. If there is a value, it will convolve. If there is no point, it do nothing.

Are all of the above statements correct?

**Comment by aniqueakhtar** [comment]
`If we set the dimension D to 3, we can say the kernel size as 3*3*3 and the kernel shape is a 3-D cube. The convolution convolves the points within the 3-D cube. If there is a value, it will convolve. If there is no point, it do nothing.

Are all of the above statements correct?
`

Seems so. Even if there is a single point, the convolution would still happen on the occupied point. Since these are sparse tensors, you also need to take care of stride. The convolution also depends on the tensor strides.

**Comment by chrischoy** [comment]
Right, it will be 3x3x3. If you want 3x3x1, specify

```python
ME.MinkowskiConvolution(in_ch, out_ch, kernel_siz=[3, 3, 1], ..., dimension=3)
```
