### ISSUE TITLE
vae example is outdated

### ISSUE THREAD

**Issue by edraizen** [NVIDIA/MinkowskiEngine#340]
**Describe the bug**
The VAE example code still contains code from v0.4.3, similar to #323. Most of the changes are easily fixed (https://gist.github.com/edraizen/c3a1898e7cf8f98e0218f45483b899b6), except for setting the tensor stride. The decoder tries to set the tensor stride on the z input variable using `z.set_tensor_stride(self.resolution)`, which does not exist in v0.5, resulting in the error:

`AttributeError: 'SparseTensor' object has no attribute 'set_tensor_stride'`

**To Reproduce**
python -m examples.vae

**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu 2004]
 - Python version: [e.g. 3.8.5]
 - CUDA version: [e.g. 11.2]
 - NVIDIA Driver version: [e.g. 460.56]
 - Minkowski Engine version [e.g. 0.5.2]

Thanks for your help,
Eli

**Comment by chrischoy** [comment]
Hi @edraizen ,

Thanks for the gist example. You did everything correctly and I updated the vae.py based on your gist.

Since the `set_tensor_stride` function modifies the coordinate map, creating a new sparse tensor as your gist did is the correct way to set the new tensor stride of a sparse tensor.
