### ISSUE TITLE
pytorch fail to install with glibc version conflicts

### ISSUE THREAD

**Issue by TerenceCYJ** [NVIDIA/MinkowskiEngine#354]
**Error**
Package wheel conflicts for:
python=3.8 -> pip -> wheel
pip -> wheelThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - pytorch=1.7.1 -> cudatoolkit[version='>=11.0,<11.1'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchvision -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.31

************************************************************************************
**To Reproduce**

Just follow https://github.com/NVIDIA/MinkowskiEngine#cuda-102

```
conda create -n py3-mink python=3.8
conda activate py3-mink

conda install openblas-devel -c anaconda
conda install pytorch=1.7.1 torchvision cudatoolkit=10.2 -c pytorch -c conda-forge
```

************************************************************************************
 - OS: Ubuntu 20.04
 - Python version: 3.8.8
 - CUDA version: 10.2
 - NVIDIA Driver version: 460.67
 - GCC version: 7.5.0

**Comment by TerenceCYJ** [comment]
The same error when using CUDA 11.2 and gcc 9.3

**Comment by abahnasy** [comment]
I'm also facing the same problem with CUDA 11.2 and gcc 9.3. Have you found any solution?

**Comment by TerenceCYJ** [comment]
> I'm also facing the same problem with CUDA 11.2 and gcc 9.3. Have you found any solution?

Hi, you can try v0.4.3.

**Comment by lilanxiao** [comment]
Hi, I just solved this issue. I think the reason is this command installed OpenBLAS in the conda environment, but it's not compatible with Pytorch:
`conda install openblas-devel -c anaconda`
My workaround is just to install OpenBLAS with a system package manager (like apt in Ubuntu) instead of using conda:
`sudo apt install libopenblas-dev`
Also, since the OpenBLAS is not installed by conda, you don't need this flag anymore. 
`--blas_include_dirs=${CONDA_PREFIX}/include`
So just remove this flag and follow the instruction. Then the code should be compiled without any issue.

**Comment by TerenceCYJ** [comment]
With cuda11.0 gcc9.3

```
conda create -n py3-cu11 python=3.8
conda activate py3-cu11
conda install -c anaconda libopenblas
conda install pytorch=1.7.1 torchvision cudatoolkit=11.0 -c pytorch -c conda-forge
git clone https://github.com/NVIDIA/MinkowskiEngine.git
cd MinkowskiEngine
TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5 8.0" python setup.py install
```
