### ISSUE TITLE
Support for H100? (TORCH_CUDA_ARCH_LIST=9.0)

### ISSUE THREAD

**Issue by jkim50104** [NVIDIA/MinkowskiEngine#588]
I'm trying to run the Minkowski engine in the H100 GPU. However, H100 has TORCH_CUDA_ARCH_LIST=9.0, and it supports from cuda 11.8. I tried running in every pytorch >= 2.0.0, cuda 11.8. I've seen environments working in this pytorch and CUDA version. I assume it is H100's compatibility problem. Did anyone succeed in this setting and GPU?

It compiles well but always asserts this error when I forward in run time.

assertion (in_feat.size(1) == kernel.size(1)) failed. Input feature size and kernel size mismatch

It can be reproduced in the H100 setting with any environment forwarding code.

 - OS: Ubuntu 22.04
 - Python version: 3.10.5
 - Pytorch version:  >= 2.0.0
 - CUDA version: 11.8
 - NVIDIA Driver version: 524
 - Minkowski Engine version 0.5.4

**Comment by zjwzcx** [comment]
Same. Have you ever solved this issue?

**Comment by jkim50104** [comment]
Hello, I did solve this issue, but it was a long time ago, so I forgot the exact issue that was causing it sorry. However, I remember that it was not the H100 compatibility problem. It still works in my H100 environment.

**Comment by D3xter1922** [comment]
Did you find any solution for this issue? I am facing the same issue @jkim50104

**Comment by leotompson** [comment]
May I ask whether the environment mentioned in the referenced issue was the one that ultimately worked? We encountered the following error when running the code on H100 GPUs, and we are unsure whether it was caused by TORCH_CUDA_ARCH_LIST=9.0.
`RuntimeError: an illegal instruction was encountered at user/path/MinkowskiEngine/src/convolution_kernel.cu:666`
